//
//  GRNotification.h
//  SmallReader
//
//  Created by Jin Jin on 10-11-11.
//  Copyright 2010 Jin Jin. All rights reserved.
//

#define NOTIFICATION_SELECTIONINMASTERVIEW @"SELECTIONINMASTERVIEW"
#define NOTIFICATION_SELECTIONINDETAILVIEW @"SELECTIONINDETAILVIEW"
#define NOTIFICATION_DELETEDOWNLOADEDSUB   @"deletedownloadedsub"
#define NOTIFICATION_SUBSCRIBEFEED		   @"SUBSCRIBEFEED"
#define NOTIFICATION_ALLRECOMMENDATIONS		@"allrecommendations"

#define NOTIFICATION_SUBSCRIBEFEED_STREAMID @"SUBSCRIBEFEEDSTREAMID"
#define NOTIFICATION_SUBSCRIBEFEED_FEEDOBJ @"SUBSCRIBEFEEDFEEDOBJ"

#define NOTIFICATION_SUBSCRIBEFEED_SUCCESS @"SUBSCRIBEFEEDSUCCESS"
#define NOTIFICATION_SUBSCRIBEFEED_FAILED @"SUBSCRIBEFEEDFAILED"

#define NOTIFICATION_SUBSCRIBEFEED_TAGSELECTED @"SUBSCRIBEFEEDTAGSELECTED"
#define NOTIFICATION_SUBSCRIBEFEED_SELECTEDTAGS @"SUBSCRIBEFEEDSELECTEDTAGS"
#define NOTIFICATION_SUBSCRIBEFEED_TITLE @"SUBSCRIBEFEEDTITLE"

#define NOTIFICATION_SUBSCRIBEFEED_CANCELLED @"SUBSCRIBEFEEDCANELLED"

#define NOTIFICATION_ADDNEWTAG_LABELNAME @"ADDNEWTAGLABELNAME"
#define NOTIFICATION_ADDNEWTAG @"ADDNEWTAG"

#define NOTIFICATION_LOGINSTATUSCHANGED @"NOTIFICATION_LOGINSTATUSCHANGED"

#define ITEMDOWNLOADFINISHED @"itemDownloadFinished"

#define CLASSNAME @"calssName"
#define INITOBJ @"initObj"
#define DETAILVIEWCONTROLLER @"detailViewController"

#define NOTIFICATION_STARITEM @"NOTIFICATION_STARITEM"
#define NOTIFICATION_STARSUCCESS @"NOTIFICATION_STARSUCCESS"
#define NOTIFICATION_STARFAILED @"NOTIFICATION_STARFAILED"
#define NOTIFICATION_UNSTARITEM @"NOTIFICATION_UNSTARITEM"
#define NOTIFICATION_UNSTARSUCCESS @"NOTIFICATION_UNSTARSUCCESS"
#define NOTIFICATION_UNSTARFAILED @"NOTIFICATION_UNSTARFAILED"
#define NOTIFICATION_READSTATESCHANGE @"NOTIFICATION_READSTATESCHANGE"
#define NOTIFICATION_SWIPEACTION_RIGHT @"NOTIFICATION_SWIPEACTION_RIGHT"
#define NOTIFICATION_SWIPEACTION_LEFT @"NOTIFICATION_SWIPEACTION_LEFT"
#define NOTIFICATION_MARKITEMASREAD @"NOTIFICATION_MARKITEMASREAD"
#define NOTIFICATION_MARKITEMASUNREAD @"NOTIFICATION_MARKITEMASUNREAD"
#define NOTIFICATION_SENDTOREADITLATER @"NOTIFICATION_SENDTOREADITLATER"
#define NOTIFICATION_SENDTOINSTAPAPER @"NOTIFICATION_SENDTOINSTAPAPER"

#define NOTIFICATION_BEGIN_UPDATESUBSCRIPTIONLIST @"NOTIFICATION_BEGIN_UPDATESUBSCRIPTIONLIST"
#define NOTIFICAITON_END_UPDATESUBSCRIPTIONLIST @"NOTIFICAITON_END_UPDATESUBSCRIPTIONLIST"
#define NOTIFICATION_BEGIN_UPDATETAGLIST @"NOTIFICATION_BEGIN_UPDATETAGLIST"
#define NOTIFICAITON_END_UPDATETAGLIST @"NOTIFICAITON_END_UPDATETAGLIST"
#define NOTIFICATION_BEGIN_UPDATEREADERSTRUCTURE @"NOTIFICATION_BEGIN_UPDATEREADERSTRUCTURE"
#define NOTIFICAITON_END_UPDATEREADERSTRUCTURE @"NOTIFICAITON_END_UPDATEREADERSTRUCTURE"
#define NOTIFICAITON_FAILED_UPDATEREADERSTRUCTURE @"NOTIFICAITON_FAILED_UPDATEREADERSTRUCTURE"
#define NOTIFICATION_BEGIN_UPDATEUNREADCOUNT @"NOTIFICATION_BEGIN_UPDATEUNREADCOUNT"
#define NOTIFICAITON_END_UPDATEUNREADCOUNT @"NOTIFICAITON_END_UPDATEUNREADCOUNT" 
#define NOTIFICATION_NEED_UPATEREADERSTRUCTURE @"NOTIFICATION_NEED_UPATEREADERSTRUCTURE"

