//
//  GRNotification.h
//  SmallReader
//
//  Created by Jin Jin on 10-11-11.
//  Copyright 2010 Jin Jin. All rights reserved.
//

#define NOTIFICATION_SELECTIONINMASTERVIEW @"SELECTIONINMASTERVIEW"
#define NOTIFICATION_SELECTIONINDETAILVIEW @"SELECTIONINDETAILVIEW"
#define NOTIFICATION_DELETEDOWNLOADEDSUB   @"deletedownloadedsub"
#define NOTIFICATION_SUBSCRIBEFEED		   @"SUBSCRIBEFEED"
#define NOTIFICATION_ALLRECOMMENDATIONS		@"allrecommendations"

#define NOTIFICATION_SUBSCRIBEFEED_STREAMID @"SUBSCRIBEFEEDSTREAMID"
#define NOTIFICATION_SUBSCRIBEFEED_FEEDOBJ @"SUBSCRIBEFEEDFEEDOBJ"

#define NOTIFICATION_SUBSCRIBEFEED_SUCCESS @"SUBSCRIBEFEEDSUCCESS"
#define NOTIFICATION_SUBSCRIBEFEED_FAILED @"SUBSCRIBEFEEDFAILED"

#define NOTIFICATION_SUBSCRIBEFEED_TAGSELECTED @"SUBSCRIBEFEEDTAGSELECTED"
#define NOTIFICATION_SUBSCRIBEFEED_SELECTEDTAGS @"SUBSCRIBEFEEDSELECTEDTAGS"
#define NOTIFICATION_SUBSCRIBEFEED_TITLE @"SUBSCRIBEFEEDTITLE"

#define NOTIFICATION_SUBSCRIBEFEED_CANCELLED @"SUBSCRIBEFEEDCANELLED"

#define NOTIFICATION_ADDNEWTAG_LABELNAME @"ADDNEWTAGLABELNAME"
#define NOTIFICATION_ADDNEWTAG @"ADDNEWTAG"

#define NOTIFICATION_LOGINSTATUSCHANGED @"NOTIFICATION_LOGINSTATUSCHANGED"

#define ITEMDOWNLOADFINISHED @"itemDownloadFinished"

#define CLASSNAME @"calssName"
#define INITOBJ @"initObj"
#define DETAILVIEWCONTROLLER @"detailViewController"

