//
//  BRViewControllerNotification.h
//  BreezyReader2
//
//  Created by 金 津 on 12-3-8.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

#define NOTIFICATION_VIEWCONTROLLER_BOOMIN @"NOTIFICATION_VIEWCONTROLLER_BOOMIN"

#define NOTIFICATION_SERACHBUTTONCLICKED @"NOTIFICATION_SERACHBUTTONCLICKED"
#define NOTIFICATION_DOWNLOADBUTTONCLICKED @"NOTIFICATION_DOWNLOADBUTTONCLICKED"
#define NOTIFICATION_LOGOUTBUTTONCLICKED @"NOTIFICATION_LOGOUTBUTTONCLICKED"
#define NOTIFICATION_CONFIGBUTTONCLICKED @"NOTIFICATION_CONFIGBUTTONCLICKED"    
#define NOTIFICATION_STARBUTTONCLICKED @"NOTIFICATION_STARBUTTONCLICKED"
#define NOTIFICATION_SHOWAUBLISTBUTTONCLICKED @"NOTIFICATION_SHOWAUBLISTBUTTONCLICKED"
#define NOTIFICATION_RELOADBUTTONCLICKED @"NOTIFICATION_RELOADBUTTONCLICKED"

#define NOTIFICATION_SEARCHCOMPLETED @"NOTIFICATION_SEARCHCOMPLETED"
#define NOTIFICATION_STARTFLIPSUBTILEVIEW @"NOTIFICATION_STARTFLIPSUBTILEVIEW"
#define NOTIFICATION_FINISHEDFLIPSUBTILEVIEW @"NOTIFICATION_FINISHEDFLIPSUBTILEVIEW"

#define NOTIFICATION_MENUACTION_UNREADONLY @"NOTIFICATION_MENUACTION_UNREADONLY"
#define NOTIFICAITON_MENUACTION_ALLARTICLES @"NOTIFICAITON_MENUACTION_ALLARTICLES"
#define NOTIFICATION_MENUACTION_MARKALLASREAD @"NOTIFICATION_MENUACTION_MARKALLASREAD" 
#define NOTIFICATION_MENUACTION_DISAPPEAR @"NOTIFICATION_MENUACTION_DISAPPEAR"

#define NOTIFICAITON_SETTING_PICKIMAGEFORBACKGROUND @"NOTIFICAITON_SETTING_PICKIMAGEFORBACKGROUND"

#define NOTIFICATION_CONFIG_UNSUBSCRIBEFEED @"NOTIFICATION_CONFIG_UNSUBSCRIBEFEED"
#define NOTIFICATION_CONFIG_RENAMEFEED @"NOTIFICATION_CONFIG_RENAMEFEED"
#define NOTIFICATION_CONFIG_ADDTAG @"NOTIFICATION_CONFIG_ADDTAG"
#define NOTIFICATION_CONFIG_REMOVETAG @"NOTIFICATION_CONFIG_REMOVETAG"

#define NOTIFICATION_FEED_UNSUBSCRIBED @"NOTIFICATION_FEED_UNSUBSCRIBED"
#define NOTIFICATION_FEED_SUBSCRIBED @"NOTIFICATION_FEED_SUBSCRIBED"

#define NOTIFICATION_SHARE_EVERNOTE @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_TWITTER @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_INSTAPAPER @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_READITLATER @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_WEIBO @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_MAIL @"NOTIFICATION_SHARE_EVERNOTE"
#define NOTIFICATION_SHARE_FACEBOOK @"NOTIFICATION_SHARE_EVERNOTE"