//
//  BRViewControllerNotification.h
//  BreezyReader2
//
//  Created by 金 津 on 12-3-8.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

#define NOTIFICATION_VIEWCONTROLLER_BOOMIN @"NOTIFICATION_VIEWCONTROLLER_BOOMIN"

#define NOTIFICATION_SERACHBUTTONCLICKED @"NOTIFICATION_SERACHBUTTONCLICKED"
#define NOTIFICATION_DOWNLOADBUTTONCLICKED @"NOTIFICATION_DOWNLOADBUTTONCLICKED"
#define NOTIFICATION_LOGOUTBUTTONCLICKED @"NOTIFICATION_LOGOUTBUTTONCLICKED"
#define NOTIFICATION_CONFIGBUTTONCLICKED @"NOTIFICATION_CONFIGBUTTONCLICKED"    

#define NOTIFICATION_SEARCHCOMPLETED @"NOTIFICATION_SEARCHCOMPLETED"
#define NOTIFICATION_STARTFLIPSUBTILEVIEW @"NOTIFICATION_STARTFLIPSUBTILEVIEW"
#define NOTIFICATION_FINISHEDFLIPSUBTILEVIEW @"NOTIFICATION_FINISHEDFLIPSUBTILEVIEW"